### ISSUE TITLE
installation: complaint about Xcode being outdated

### ISSUE THREAD

**Issue by cecileane** [justincbagley/PIrANHA#7]
I am trying to install piranha using brew, following the steps in the instructions.
I get the following error:
```
% brew install piranha
==> Downloading https://github.com/justincbagley/piranha/archive/v0.4a4.tar.gz
Already downloaded: /Users/ane/Library/Caches/Homebrew/downloads/cb10bb7440d1ac9236326cea7164c4978ee12ccee59a49738828a4941b37c42c--piranha-0.4a4.tar.gz
==> Installing piranha from justincbagley/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.
```

After the first time I got this, I re-installed Xcode using `softwareupdate --all --install --force`. I restarted my machine, and re-tried the installation command `brew install piranha` but got the same error again.
I also updated brew with `brew update` and `brew upgrade` (which run fine without any warnings or errors).
I now have Xcode 13.2.1, which is higher than 13.1 mentioned in the error message so it should be sufficient (I hope!) and I didn't try re-installing Xcode again in some other way.

### Machine

That's on macOS Big Sur 11.6.2.
I am using zsh v5.8

I'm not sure what other information would be helpful.

I would love to be able to use PIrANHA!

**Comment by justincbagley** [comment]
Hi Cécile,

This is a new issue for me re `piranha`, but it seems to have been a persistent and common issue with Homebrew installs over the past 5+ years. I found some threads containing suggestions for this issue and they are older but the solutions might still work. Here they are:

 -   https://stackoverflow.com/questions/15417619/how-do-you-update-xcode-on-osx-to-the-latest-version/56252014#56252014
 -   https://stackoverflow.com/questions/40296756/homebrew-saying-xcode-is-outdated

The key piece of advice that seems to have worked for others is to delete the `check_xcode_minimum_version` line from the following block in the Homebrew diagnostic ruby file at `/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb`...

```
      def fatal_build_from_source_checks
        %w[
          check_xcode_license_approved
          check_xcode_minimum_version
          check_clt_minimum_version
          check_if_xcode_needs_clt_installed
          check_if_supported_sdk_available
          check_broken_sdks
        ].freeze
      end
```

Try this approach and let me know if it works. Thanks.

Best,
~J

**Comment by cecileane** [comment]
Oh wow, I didn't know it was a homebrew problem. I am sorry for bothering you with this.

So removing the line `check_xcode_minimum_version` did not fix the problem, but I will look into it further. Thanks for the diagnostic!

**Comment by justincbagley** [comment]
Hi Cecile,

Did you find another fix and get the `piranha` install working? If not, then I am happy to continue working with you on this. What error message are you getting now, the same or a different one?

Best, 
~J

**Comment by justincbagley** [comment]
Also I am wondering about your `xcode` tools... and I think some print outs would be helpful. On your machine, what is the output of:

`xcode-select -p`

and 

`xcode-select -v`?

~J

**Comment by cecileane** [comment]
My time was taken over by other commitments after the calm of the end-of-the-year, so I have not tried further. Fortunately my collaborator @laufran got piranha to work on her machine 😉 She told me she got an error message with the suggested installation method `brew install piranha` (not the error I got though, so it's a digression), but the installation worked using the development version `brew install --HEAD piranha`.

I'm expecting more trouble if I need to re-install XCode, because my mac now complains that I haven't enough space (XCode is insanely large). But here is the information I got:
```shell
% xcode-select -p
/Library/Developer/CommandLineTools
% xcode-select -v
xcode-select version 2384.
```
Given that the problem is with brew, not piranha, this comment could be closed. Or if it's not too tricky to install piranha without homebrew, it'd be great to include instructions for doing so.

**Comment by cecileane** [comment]
Oh, I forgot to say that I get the same error as earlier, after deleting either or both lines with `check_xcode_minimum_version` in `/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb`, as shown below.

```
% brew install piranha
==> Downloading https://github.com/justincbagley/piranha/archive/v0.4a4.tar.gz
Already downloaded: /Users/ane/Library/Caches/Homebrew/downloads/cb10bb7440d1ac9236326cea7164c4978ee12ccee59a49738828a4941b37c42c--piranha-0.4a4.tar.gz
==> Installing piranha from justincbagley/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.
```

When I delete the line with `check_clt_minimum_version` from function `fatal_build_from_source_checks`, still in the same `diagnostic.rb` file, brew restores my changes automatically and then I get the error:

```
% brew install piranha
Running `brew update --preinstall`...
To restore the stashed changes to /usr/local/Homebrew, run:
  cd /usr/local/Homebrew && git stash pop
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://github.com/justincbagley/piranha/archive/v0.4a4.tar.gz
Already downloaded: /Users/ane/Library/Caches/Homebrew/downloads/cb10bb7440d1ac9236326cea7164c4978ee12ccee59a49738828a4941b37c42c--piranha-0.4a4.tar.gz
==> Installing piranha from justincbagley/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.
```

but... not always. Trying again, brew did *not* restore my change. so I got a warning then an error:
```
% brew install piranha
==> Downloading https://github.com/justincbagley/piranha/archive/v0.4a4.tar.gz
Already downloaded: /Users/ane/Library/Caches/Homebrew/downloads/cb10bb7440d1ac9236326cea7164c4978ee12ccee59a49738828a4941b37c42c--piranha-0.4a4.tar.gz
==> Installing piranha from justincbagley/tap
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

Error: An exception occurred within a child process:
  SystemExit: exit
```
Again, feel free to close the issue, because it's about brew!
